C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.2.6)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapagud (agudf2pywrap, g)
      external agud
      double precision g
      double precision agudf2pywrap
      double precision  agud
      agudf2pywrap = agud(g)
      end


      subroutine f2pywrapalign_enum (align_enumf2pywrap, m, n)
      external align_enum
      integer m
      integer n
      integer align_enumf2pywrap
      integer  align_enum
      align_enumf2pywrap = align_enum(m, n)
      end


      subroutine f2pywrapbenford (benfordf2pywrap, ival)
      external benford
      integer ival
      double precision benfordf2pywrap
      double precision  benford
      benfordf2pywrap = benford(ival)
      end


      subroutine f2pywrapcatalan_constant (catalan_constantf2pywra
     &p)
      external catalan_constant
      double precision catalan_constantf2pywrap
      double precision  catalan_constant
      catalan_constantf2pywrap = catalan_constant()
      end


      subroutine f2pywrapcollatz_count (collatz_countf2pywrap, n)
      external collatz_count
      integer n
      integer collatz_countf2pywrap
      integer  collatz_count
      collatz_countf2pywrap = collatz_count(n)
      end


      subroutine f2pywrapcos_power_int (cos_power_intf2pywrap, a, 
     &b, n)
      external cos_power_int
      double precision a
      double precision b
      integer n
      double precision cos_power_intf2pywrap
      double precision  cos_power_int
      cos_power_intf2pywrap = cos_power_int(a, b, n)
      end


      subroutine f2pywrapeuler_number2 (euler_number2f2pywrap, n)
      external euler_number2
      integer n
      double precision euler_number2f2pywrap
      double precision  euler_number2
      euler_number2f2pywrap = euler_number2(n)
      end


      subroutine f2pywrapeuler_poly (euler_polyf2pywrap, n, x)
      external euler_poly
      integer n
      double precision x
      double precision euler_polyf2pywrap
      double precision  euler_poly
      euler_polyf2pywrap = euler_poly(n, x)
      end


      subroutine f2pywrapgud (gudf2pywrap, x)
      external gud
      double precision x
      double precision gudf2pywrap
      double precision  gud
      gudf2pywrap = gud(x)
      end


      subroutine f2pywrapi4_choose (i4_choosef2pywrap, n, k)
      external i4_choose
      integer n
      integer k
      integer i4_choosef2pywrap
      integer  i4_choose
      i4_choosef2pywrap = i4_choose(n, k)
      end


      subroutine f2pywrapi4_factorial (i4_factorialf2pywrap, n)
      external i4_factorial
      integer n
      integer i4_factorialf2pywrap
      integer  i4_factorial
      i4_factorialf2pywrap = i4_factorial(n)
      end


      subroutine f2pywrapi4_factorial2 (i4_factorial2f2pywrap, n)
      external i4_factorial2
      integer n
      integer i4_factorial2f2pywrap
      integer  i4_factorial2
      i4_factorial2f2pywrap = i4_factorial2(n)
      end


      subroutine f2pywrapi4_huge (i4_hugef2pywrap)
      external i4_huge
      integer i4_hugef2pywrap
      integer  i4_huge
      i4_hugef2pywrap = i4_huge()
      end


      subroutine f2pywrapi4_is_prime (i4_is_primef2pywrap, n)
      external i4_is_prime
      integer n
      logical i4_is_primef2pywrap
      logical  i4_is_prime
      i4_is_primef2pywrap = .not.(.not.i4_is_prime(n))
      end


      subroutine f2pywrapi4_is_triangular (i4_is_triangularf2pywra
     &p, i)
      external i4_is_triangular
      integer i
      logical i4_is_triangularf2pywrap
      logical  i4_is_triangular
      i4_is_triangularf2pywrap = .not.(.not.i4_is_triangular(i))
      end


      subroutine f2pywrapi4_uniform_ab (i4_uniform_abf2pywrap, a, 
     &b, seed)
      external i4_uniform_ab
      integer a
      integer b
      integer seed
      integer i4_uniform_abf2pywrap
      integer  i4_uniform_ab
      i4_uniform_abf2pywrap = i4_uniform_ab(a, b, seed)
      end


      subroutine f2pywraplambert_w (lambert_wf2pywrap, x)
      external lambert_w
      double precision x
      double precision lambert_wf2pywrap
      double precision  lambert_w
      lambert_wf2pywrap = lambert_w(x)
      end


      subroutine f2pywraplambert_w_crude (lambert_w_crudef2pywrap,
     & x)
      external lambert_w_crude
      double precision x
      double precision lambert_w_crudef2pywrap
      double precision  lambert_w_crude
      lambert_w_crudef2pywrap = lambert_w_crude(x)
      end


      subroutine f2pywraplerch (lerchf2pywrap, z, s, a)
      external lerch
      double precision z
      integer s
      double precision a
      double precision lerchf2pywrap
      double precision  lerch
      lerchf2pywrap = lerch(z, s, a)
      end


      subroutine f2pywrapmertens (mertensf2pywrap, n)
      external mertens
      integer n
      integer mertensf2pywrap
      integer  mertens
      mertensf2pywrap = mertens(n)
      end


      subroutine f2pywrapnormal_01_cdf_inverse (normal_01_cdf_inve
     &rsef2pywrap, p)
      external normal_01_cdf_inverse
      double precision p
      double precision normal_01_cdf_inversef2pywrap
      double precision  normal_01_cdf_inverse
      normal_01_cdf_inversef2pywrap = normal_01_cdf_inverse(p)
      end


      subroutine f2pywrapplane_partition_num (plane_partition_numf
     &2pywrap, n)
      external plane_partition_num
      integer n
      integer plane_partition_numf2pywrap
      integer  plane_partition_num
      plane_partition_numf2pywrap = plane_partition_num(n)
      end


      subroutine f2pywrappoly_coef_count (poly_coef_countf2pywrap,
     & dim, degree)
      external poly_coef_count
      integer dim
      integer degree
      integer poly_coef_countf2pywrap
      integer  poly_coef_count
      poly_coef_countf2pywrap = poly_coef_count(dim, degree)
      end


      subroutine f2pywrapprime (primef2pywrap, n)
      external prime
      integer n
      integer primef2pywrap
      integer  prime
      primef2pywrap = prime(n)
      end


      subroutine f2pywrappyramid_num (pyramid_numf2pywrap, n)
      external pyramid_num
      integer n
      integer pyramid_numf2pywrap
      integer  pyramid_num
      pyramid_numf2pywrap = pyramid_num(n)
      end


      subroutine f2pywrappyramid_square_num (pyramid_square_numf2p
     &ywrap, n)
      external pyramid_square_num
      integer n
      integer pyramid_square_numf2pywrap
      integer  pyramid_square_num
      pyramid_square_numf2pywrap = pyramid_square_num(n)
      end


      subroutine f2pywrapr8_agm (r8_agmf2pywrap, a, b)
      external r8_agm
      double precision a
      double precision b
      double precision r8_agmf2pywrap
      double precision  r8_agm
      r8_agmf2pywrap = r8_agm(a, b)
      end


      subroutine f2pywrapr8_beta (r8_betaf2pywrap, x, y)
      external r8_beta
      double precision x
      double precision y
      double precision r8_betaf2pywrap
      double precision  r8_beta
      r8_betaf2pywrap = r8_beta(x, y)
      end


      subroutine f2pywrapr8_choose (r8_choosef2pywrap, n, k)
      external r8_choose
      integer n
      integer k
      double precision r8_choosef2pywrap
      double precision  r8_choose
      r8_choosef2pywrap = r8_choose(n, k)
      end


      subroutine f2pywrapr8_epsilon (r8_epsilonf2pywrap)
      external r8_epsilon
      double precision r8_epsilonf2pywrap
      double precision  r8_epsilon
      r8_epsilonf2pywrap = r8_epsilon()
      end


      subroutine f2pywrapr8_erf (r8_erff2pywrap, x)
      external r8_erf
      double precision x
      double precision r8_erff2pywrap
      double precision  r8_erf
      r8_erff2pywrap = r8_erf(x)
      end


      subroutine f2pywrapr8_erf_inverse (r8_erf_inversef2pywrap, y
     &)
      external r8_erf_inverse
      double precision y
      double precision r8_erf_inversef2pywrap
      double precision  r8_erf_inverse
      r8_erf_inversef2pywrap = r8_erf_inverse(y)
      end


      subroutine f2pywrapr8_euler_constant (r8_euler_constantf2pyw
     &rap)
      external r8_euler_constant
      double precision r8_euler_constantf2pywrap
      double precision  r8_euler_constant
      r8_euler_constantf2pywrap = r8_euler_constant()
      end


      subroutine f2pywrapr8_factorial (r8_factorialf2pywrap, n)
      external r8_factorial
      integer n
      double precision r8_factorialf2pywrap
      double precision  r8_factorial
      r8_factorialf2pywrap = r8_factorial(n)
      end


      subroutine f2pywrapr8_factorial_log (r8_factorial_logf2pywra
     &p, n)
      external r8_factorial_log
      integer n
      double precision r8_factorial_logf2pywrap
      double precision  r8_factorial_log
      r8_factorial_logf2pywrap = r8_factorial_log(n)
      end


      subroutine f2pywrapr8_gamma_log (r8_gamma_logf2pywrap, x)
      external r8_gamma_log
      double precision x
      double precision r8_gamma_logf2pywrap
      double precision  r8_gamma_log
      r8_gamma_logf2pywrap = r8_gamma_log(x)
      end


      subroutine f2pywrapr8_huge (r8_hugef2pywrap)
      external r8_huge
      double precision r8_hugef2pywrap
      double precision  r8_huge
      r8_hugef2pywrap = r8_huge()
      end


      subroutine f2pywrapr8_mop (r8_mopf2pywrap, i)
      external r8_mop
      integer i
      double precision r8_mopf2pywrap
      double precision  r8_mop
      r8_mopf2pywrap = r8_mop(i)
      end


      subroutine f2pywrapr8_nint (r8_nintf2pywrap, x)
      external r8_nint
      double precision x
      integer r8_nintf2pywrap
      integer  r8_nint
      r8_nintf2pywrap = r8_nint(x)
      end


      subroutine f2pywrapr8_pi (r8_pif2pywrap)
      external r8_pi
      double precision r8_pif2pywrap
      double precision  r8_pi
      r8_pif2pywrap = r8_pi()
      end


      subroutine f2pywrapr8_psi (r8_psif2pywrap, xx)
      external r8_psi
      double precision xx
      double precision r8_psif2pywrap
      double precision  r8_psi
      r8_psif2pywrap = r8_psi(xx)
      end


      subroutine f2pywrapr8_uniform_01 (r8_uniform_01f2pywrap, see
     &d)
      external r8_uniform_01
      integer seed
      double precision r8_uniform_01f2pywrap
      double precision  r8_uniform_01
      r8_uniform_01f2pywrap = r8_uniform_01(seed)
      end


      subroutine f2pywrapr8poly_degree (r8poly_degreef2pywrap, na,
     & a)
      external r8poly_degree
      integer na
      double precision a(1 + na)
      integer r8poly_degreef2pywrap
      integer  r8poly_degree
      r8poly_degreef2pywrap = r8poly_degree(na, a)
      end


      subroutine f2pywrapr8poly_value_horner (r8poly_value_hornerf
     &2pywrap, m, c, x)
      external r8poly_value_horner
      integer m
      double precision x
      double precision c(1 + m)
      double precision r8poly_value_hornerf2pywrap
      double precision  r8poly_value_horner
      r8poly_value_hornerf2pywrap = r8poly_value_horner(m, c, x)
      end


      subroutine f2pywraps_len_trim (s_len_trimf2pywrap, s)
      external s_len_trim
      character*(*) s
      integer s_len_trimf2pywrap
      integer  s_len_trim
      s_len_trimf2pywrap = s_len_trim(s)
      end


      subroutine f2pywrapsimplex_num (simplex_numf2pywrap, m, n)
      external simplex_num
      integer m
      integer n
      integer simplex_numf2pywrap
      integer  simplex_num
      simplex_numf2pywrap = simplex_num(m, n)
      end


      subroutine f2pywrapsin_power_int (sin_power_intf2pywrap, a, 
     &b, n)
      external sin_power_int
      double precision a
      double precision b
      integer n
      double precision sin_power_intf2pywrap
      double precision  sin_power_int
      sin_power_intf2pywrap = sin_power_int(a, b, n)
      end


      subroutine f2pywraptetrahedron_num (tetrahedron_numf2pywrap,
     & n)
      external tetrahedron_num
      integer n
      integer tetrahedron_numf2pywrap
      integer  tetrahedron_num
      tetrahedron_numf2pywrap = tetrahedron_num(n)
      end


      subroutine f2pywraptriangle_num (triangle_numf2pywrap, n)
      external triangle_num
      integer n
      integer triangle_numf2pywrap
      integer  triangle_num
      triangle_numf2pywrap = triangle_num(n)
      end


      subroutine f2pywraptrinomial (trinomialf2pywrap, i, j, k)
      external trinomial
      integer i
      integer j
      integer k
      integer trinomialf2pywrap
      integer  trinomial
      trinomialf2pywrap = trinomial(i, j, k)
      end


      subroutine f2pywrapzeta (zetaf2pywrap, p)
      external zeta
      double precision p
      double precision zetaf2pywrap
      double precision  zeta
      zetaf2pywrap = zeta(p)
      end

